server:
  port: 9090

logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.messaging.simp.broker: DEBUG
    com.daollar.orderentry: DEBUG
    org.apache.kafka: INFO
    com.amblelogistic.Mapper: DEBUG
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/marlabs?autoReconnect=true"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 5

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    pool:
    timeout: 2000
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
        maxTotal: 500
        maxWaitMillis: 3000
        testOnBorrow: true

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.amblelogistic.Model

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

token:
  valid:
    time: 2

interface:
  type: test

